[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flask_jsglue"

version = "2.1.0"

description = "Flask-JSGlue helps hook up your Flask application nicely with the front end."

readme = "README.md"

requires-python = ">=3.11"

license = { text = "BSD-3-Clause" }

keywords = ["Flask", "JavaScript"]

authors = [
    { name = "Stewart Park", email = "stewartpark92@gmail.com"},
    { name = "Brett Tolbert", email = "bretttolbert@gmail.com" }
]

maintainers = [
  { name = "Brett Tolbert", email = "bretttolbert@gmail.com" },
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
]

dependencies = ["Flask"]

[project.optional-dependencies]
dev = ["check-manifest", "black", "isort", "coverage", "pytest", "mypy"]

[project.urls]
"Homepage" = "https://github.com/bretttolbert/Flask_JSGlue"
"Bug Reports" = "https://github.com/bretttolbert/Flask_JSGlue/issues"
"Source" = "https://github.com/bretttolbert/Flask_JSGlue/"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages]
find = {where = ["src"]}

[tool.setuptools.package-data]
flask_jsglue = ["py.typed", "main/templates/*"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
pythonpath = [
  "src"
]
testpaths = [
    "test",
]
